name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm install

      - name: Run unit tests and generate code coverage report
        run: npm run test -- --coverage

      - name: Publish code coverage report
        uses: codecov/codecov-action@v1

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    needs: test
    steps:
      - name: Release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Generate documentation
        run: npm run docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
